### Matthew Riddell 
### D00245674
### MSc in Data Analytics
### Dissertation
### Initial Data Modelling Jupyter Notebook

Initial Data Modelling conducted for the Interim Report

After conducting Data Exploration I conducted an ANOVA test to check variance across each petition

I then created two Linear Regression Models

Model 1: This one compares raw Signatures against GDP + Population

Model 2: This one compares Signatures per Capita against GDP_Per_Capita + Unemployment_Rate + Tertiary_Enrollment + Life_Expectancy + Population_Density

I then evaluated the results using RMSE and R Squared

I found that while GDP and Population do influence variation in overall Signature counts

Once you account for population size, the socio-economic variables selected do little to explain variance on a per capita basis

The ANOVA then further supports the notion that the biggest variation is down to petition specific factors

For future work I will need to expand by incorporating new variables and examine how those influence signature rates

### Link to each Dataset:

### ECI Petitions:
#### 2024

- ECI 01: https://citizens-initiative.europa.eu/initiatives/details/2024/000001_en Ban on conversion practices in the European Union
- ECI 02: https://citizens-initiative.europa.eu/initiatives/details/2024/000002_en European Citizens' Initiative in Defence of Agriculture and Rural Economy in Europe
- ECI 03: https://citizens-initiative.europa.eu/initiatives/details/2024/000004_en My Voice, My Choice: For Safe And Accessible Abortion
- ECI 04: https://citizens-initiative.europa.eu/initiatives/details/2024/000006_en Air-Quotas
- ECI 05: https://citizens-initiative.europa.eu/initiatives/details/2024/000007_en Stop Destroying Videogames
- ECI 06: https://citizens-initiative.europa.eu/initiatives/details/2024/000008_en Stop Cruelty Stop Slaughter
- ECI 07: https://citizens-initiative.europa.eu/initiatives/details/2024/000009_en STOP FAKE FOOD: ORIGIN ON LABEL
- ECI 08: https://citizens-initiative.europa.eu/initiatives/details/2024/000010_en ECI for a Water-Smart and Resilient Europe
- ECI 09: https://citizens-initiative.europa.eu/initiatives/details/2024/000011_en PsychedeliCare

#### 2023

- ECI 10: https://citizens-initiative.europa.eu/initiatives/details/2023/000001_en Stop torture and inhuman treatment at Europe’s borders
- ECI 11: https://citizens-initiative.europa.eu/initiatives/details/2023/000002_en Ensuring a dignified reception of migrants in Europe
- ECI 12: https://citizens-initiative.europa.eu/initiatives/details/2023/000003_en End The Horse Slaughter Age
- ECI 13: https://citizens-initiative.europa.eu/initiatives/details/2023/000004_en Connecting all European capitals and people through a high-speed train network
- ECI 14: https://citizens-initiative.europa.eu/initiatives/details/2023/000005_en Effective implementation of the concept of judicial precedent in EU countries
- ECI 15: https://citizens-initiative.europa.eu/initiatives/details/2023/000006_en Taxing great wealth to finance the ecological and social transition
- ECI 16: https://citizens-initiative.europa.eu/initiatives/details/2023/000007_en Preservation and development of Ukrainian culture, education, language, and traditions in EU states
- ECI 17: https://citizens-initiative.europa.eu/initiatives/details/2023/000008_en EU Live Bus Stop Info
- ECI 18: https://citizens-initiative.europa.eu/initiatives/details/2023/000009_en Trust and Freedom
- ECI 19: https://citizens-initiative.europa.eu/initiatives/details/2023/000011_en Creation of a European Environment Authority

#### 2022

- ECI 20: https://citizens-initiative.europa.eu/initiatives/details/2022/000001_en Win It On The Pitch 
- ECI 21: https://citizens-initiative.europa.eu/initiatives/details/2022/000002_en Fur Free Europe
- ECI 22: https://citizens-initiative.europa.eu/initiatives/details/2022/000003_en End The Slaughter Age
- ECI 23: https://citizens-initiative.europa.eu/initiatives/details/2022/000004_en Good Clothes, Fair Pay
- ECI 24: https://citizens-initiative.europa.eu/initiatives/details/2022/000007_en Protect the EU’s Rural Heritage, Food Security and Supply
- ECI 25: https://citizens-initiative.europa.eu/initiatives/details/2022/000008_en Focus on Specific Learning Disabilities on EU Level
- ECI 26: https://citizens-initiative.europa.eu/initiatives/details/2022/000009_en European Citizens’ Initiative for VEGAN MEAL
- ECI 27: https://citizens-initiative.europa.eu/initiatives/details/2022/000010_en European Day of "Whatever it Takes" 

### Worldstat Kaggle Dataset
https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

### Mahara Portfolio:
https://mahara.dkit.ie/view/view.php?t=f816cb6da6dd833aaa2f

### Github Repository:
https://github.com/Matthew-Riddell/MSc-Dissertation

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import statsmodels.api as sm

import scipy
from scipy.stats import f_oneway
import joblib

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

### Model path for Model Exporting

In [2]:
model_path = r"C:\Users\Matty\Documents\College Notes & Assignments\Year 5\Dissertation\MSc-Dissertation\models"

### File path for Importing Dataset

In [3]:
file_path = "C:/Users/Matty/Documents/College Notes & Assignments/Year 5/Dissertation/MSc-Dissertation/data/Prepared Datasets/"
file_name = "eci_merged_dataset.csv"
complete_file_name = file_path + file_name

In [4]:
merged_data = pd.read_csv(complete_file_name)

In [5]:
merged_data.head()

,Country,Signatures,Threshold,Percentage,Petition_ID,Population,GDP,Population_Density,Unemployment_Rate,Tertiary_Enrollment,Life_Expectancy,Urban_Population,Labor_Participation,Signatures_Per_Capita,GDP_Per_Capita,Threshold_Ratio,Threshold_Per_Capita,Petition_Name
0,Austria,10724,13395,80.06,eci_table_01,8877067.0,4.463147e+11,109,4.67,85.1,81.6,5194416.0,60.7,0.001208,50277.275087,0.800597,0.001509,Ban Conversion Practices
1,Belgium,47459,14805,320.56,eci_table_01,11484055.0,5.296067e+11,383,5.59,79.7,81.6,11259082.0,53.6,0.004133,46116.699234,3.205606,0.001289,Ban Conversion Practices
2,Bulgaria,2386,11985,19.91,eci_table_01,6975761.0,8.600000e+10,64,4.34,71.0,74.9,5256027.0,55.4,0.000342,12328.404026,0.199082,0.001718,Ban Conversion Practices
3,Croatia,8574,8460,101.35,eci_table_01,4067500.0,6.041555e+10,73,6.93,67.9,78.1,2328318.0,51.2,0.002108,14853.239837,1.013475,0.002080,Ban Conversion Practices
4,Cyprus,696,4230,16.45,eci_table_01,1198575.0,2.456465e+10,131,7.27,75.9,80.8,800708.0,63.1,0.000581,20494.877613,0.164539,0.003529,Ban Conversion Practices

### ANOVA
Research Question

Do different ECI petitions exhibit significantly different participation rates?

#### Hypotheses:

H0

All petitions have the same mean signatures per capita

H1

At least one petition has a different mean signatures per capita

### Prepare Petition Groups

In [6]:
petition_groups = []

for petition in merged_data["Petition_Name"].unique():

    group = merged_data[
        merged_data["Petition_Name"] == petition
    ]["Signatures_Per_Capita"]

    petition_groups.append(group)

### Run ANOVA

In [7]:
f_stat, p_value = f_oneway(*petition_groups)

print("F-statistic:", f_stat)
print("P-value:", p_value)

F-statistic: nan
P-value: nan

C:\Users\Matty\AppData\Local\Temp\ipykernel_21724\4153469853.py:1: SmallSampleWarning: One or more sample arguments is too small; all returned values will be NaN. See documentation for sample size requirements.
  f_stat, p_value = f_oneway(*petition_groups)

### Hypothesis Test

In [8]:
if p_value < 0.05:
    print(
        "Significant difference between petitions"
    )
else:
    print(
        "No significant difference between petitions"
    )

No significant difference between petitions

p < 0.05 this means that we reject the Null Hypothesis 

This means that there is significant difference in participation rates between petitions

This suggests that the greatest variation in participation comes down to petition level factors

### Linear Regression Model 1
Research Question

Can country size and economic size explain raw signature counts?


#### Hypotheses:

H0

Population size and economic size do not explain a significant proportion of the variation in raw signature counts

H1

Population size and economic indicators explain a significant portion of the variation in raw signature counts

### Setting the Linear Regression Variables

In [9]:
X = merged_data[
    [
        "Population",
        "GDP"
    ]
]

y = merged_data[
    "Signatures"
]

### Splitting the data into training and testing sets

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

### Fitting and training the model

In [11]:
model1 = LinearRegression()

model1.fit(
    X_train,
    y_train
)

LinearRegression()

### Making predictions

In [12]:
y_pred = model1.predict(X_test)

### Evaluation Metrics

In [13]:
r2_model1 = r2_score(
    y_test,
    y_pred
)

rmse = mean_squared_error(
    y_test,
    y_pred
) ** 0.5

print("R²:", r2_model1)
print("RMSE:", rmse)

R²: 0.2559264111344689
RMSE: 80927.37968796713

### Display Coefficients

In [14]:
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model1.coef_
})

coef_df

      Feature   Coefficient
0  Population  1.428093e-03
1         GDP  1.327277e-10

### Evaluation

Model 1: Raw Signatures (R squared = 0.256)

Population and GDP explain roughly 25.6% of the variation in signature counts


The model explains a moderate amount of variance

This shows that country size and gdp contribute to overall differences in signatures between countries, however it still leaves a lot of unexplained variance 

As it explains roughly 25.6% of the variance a significant portion of the variance, the null hypothesis gets rejected

### Linear Regression Model 2
Research Question

Can socio-economic indicators explain participation rates?

#### Hypotheses: 

H0

Socio-economic indicators have no significant relationship with participation rates when participation is normalised by population

H1

Socio-economic indicators have limited explanatory power when participation is normalised by population

### Setting the Linear Regression variables

In [15]:
X = merged_data[
    [
        "GDP_Per_Capita",
        "Unemployment_Rate",
        "Tertiary_Enrollment",
        "Life_Expectancy",
        "Population_Density"
    ]
]

y = merged_data[
    "Signatures_Per_Capita"
]

### Splitting the data into training and testing sets

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

### Fitting and training the model

In [17]:
model2 = LinearRegression()

model2.fit(
    X_train,
    y_train
)

LinearRegression()

### Model Predictions

In [18]:
y_pred = model2.predict(X_test)

### Evaluation Metrics

In [19]:
r2_model2 = r2_score(
    y_test,
    y_pred
)

rmse = mean_squared_error(
    y_test,
    y_pred
) ** 0.5

print("R Squared:", r2_model2)
print("RMSE:", rmse)

R Squared: -0.0449226157053797
RMSE: 0.004819432044604331

### Displaying Coefficients

In [20]:
coef_df = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": model2.coef_
})

coef_df

               Feature   Coefficient
0       GDP_Per_Capita  1.448525e-08
1    Unemployment_Rate -2.456284e-05
2  Tertiary_Enrollment  4.130855e-06
3      Life_Expectancy  9.710421e-05
4   Population_Density  4.821347e-07

### Evaluation

Model 2: Signatures Per Capita (R squared = -0.045)

The signatures per capita model achieved an R squared value of -0.045

this shows that the selected socio-economic variables fail to explain variance in signatures per capita

Failure to reject the null hypothesis

### Compare Models

In [21]:
results = pd.DataFrame({
    "Model": [
        "Raw Signatures",
        "Signatures Per Capita"
    ],
    "R Squared": [
        r2_model1,
        r2_model2
    ]
})

results

                   Model  R Squared
0         Raw Signatures   0.255926
1  Signatures Per Capita  -0.044923


The contrast between the two models suggests that the country size influences the total number of signatures collected 

but doesn't exactly influence participation rates once population difference is accounted for

### Export Models

In [22]:
# https://apxml.com/courses/basics-ml-deployment/chapter-2-preparing-model-deployment/using-joblib-persistence

joblib.dump(
    model1,
    rf"{model_path}\model_raw_signatures.pkl"
)

joblib.dump(
    model2,
    rf"{model_path}\model_signatures_per_capita.pkl"
)

print("Models exported successfully.")

Models exported successfully.

The results for each of the models tells me that

ECI participation appears to be driven more strongly by petition specific characteristics than by socio-economic condition

For future work I would like to explore further by: 

increasing the number of petitions

incorporating new variables such as media literacy, internet engagement and petition level variables

explore the relationships using other models etc.